### ISSUE TITLE
Autocomplete on diagnostics and traitaments

### ISSUE THREAD

**Issue by taniarv** [thooby/Dispensaire#10]
Substitute select fields with autocompletes for diagnostics and traitaments fields in new consultation form. 

Consider adding a new select for group of traitaments.

**Comment by taniarv** [comment]
Done

**Comment by taniarv** [comment]
Add spinner

**Comment by taniarv** [comment]
There are multiple problems with the layout/design (many p, many div, nested elements, very difficult to align items with my little CSS knowledge). We should consider **using tables** to define forms.

**Comment by thooby** [comment]
eliminated #label { display: block; } in flutie.css that add some order
