### ISSUE TITLE
Select fields in forms

### ISSUE THREAD

**Issue by taniarv** [thooby/Dispensaire#2]
All **select input fields** in forms, when no default value, should have **":include_blank => true"** as option, in order to prevent wrong values being inserted in database. For example:

`<%= f.collection_select(:village_id, @villages, :id, :nom, :include_blank => true) %>`
`

**Comment by thooby** [comment]
Included  ":include_blank => true" in the "collection_select"

I don't know how to   ":include_blank => true" when I have not "collection_select". Example in communes or villages in patients/new

**Comment by taniarv** [comment]
The same: ":include_blank => true"
